### ISSUE TITLE
NCBI and taxname signatures are all length <= 1

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBExports#13]
Only the *_metaphlan.gmt signatures seem to be correct. See for example:
* https://github.com/waldronlab/BugSigDBExports/blob/main/bugsigdb_signatures_genus_ncbi.gmt
* https://github.com/waldronlab/BugSigDBExports/blob/main/bugsigdb_signatures_genus_ncbi_exact.gmt
* https://github.com/waldronlab/BugSigDBExports/blob/main/bugsigdb_signatures_mixed_ncbi.gmt
* https://github.com/waldronlab/BugSigDBExports/blob/main/bugsigdb_signatures_mixed_taxname.gmt

**Comment by lgeistlinger** [comment]
Thanks for spotting that. I've introduced a fix that should resolve this in tomorrow's export. I believe we will also need to update this on zenodo @jwokaty.

**Comment by lwaldron** [comment]
Looks good. Issue will be closed with creation of a new Zenodo release.

**Comment by jwokaty** [comment]
I've published the new versions of the file at https://zenodo.org/record/5904281.

**Comment by lwaldron** [comment]
Thanks both! As a curiosity, do you know why Zenodo shows the wrong date (Jan 2) for v1.0.2? Not important, although if it's something on our side it'd be nice to fix for future releases.

![image](https://user-images.githubusercontent.com/639942/151172433-a8374c13-7bd8-4ddc-9024-7a24ded1cbba.png)

**Comment by jwokaty** [comment]
I forgot to update the date. I wrote to Zenodo and asked if it's possible to change the date without creating another DOI/version.
