### ISSUE TITLE
zenodo citation

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDBExports#17]
Hi @jwokaty, minor point, but can we get the [author order / citation on zenodo](https://zenodo.org/record/6468009#.Y73uuOLML6Y) to match the [author order on the manuscript](https://www.medrxiv.org/content/10.1101/2022.10.24.22281483v2)?

Currently it is:

Waldron, Levi, Jones, Heidi, Geistlinger, Ludwig, Davis, Sean, Huttenhower, Curtis, & Segata, Nicola. (2022). waldronlab/BugSigDBExports: Release v1.1.0 (v1.1.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.6468009

But should be:

Geistlinger, Ludwig, Jones, Heidi, Davis, Sean, Segata, Nicola, Huttenhower, Curtis, & Waldron, Levi. (2022). waldronlab/BugSigDBExports: Release v1.1.0 (v1.1.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.6468009

Thanks!

**Comment by jwokaty** [comment]
Thanks for noticing this. I've reordered. I just want to note here in case it ever happens again that you apparently need to hit the save button after reordering before hitting publish for the ordering to take effect.

**Comment by lgeistlinger** [comment]
Thanks!
