### ISSUE TITLE
Can the main branch be renamed to devel?

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDBExports#21]
Hi @jwokaty - can we rename the `main` branch of BugSigDBExports to `devel`?

This would be beneficial as it 

1. would align with the notation used in `bugsigdbr::importBugSigDB(version = "devel")`,
2. would simplify some code in `bugsigdbr::importBugSigDB` as it would make [Line 31](https://github.com/waldronlab/bugsigdbr/blob/b4bb24abd395f20951dc8a1ead281a799befba5c/R/bugsigdb.R#L31) obsolete.

**Comment by jwokaty** [comment]
Sorry I didn't see this sooner. We can do this with some coordination.

**Comment by lgeistlinger** [comment]
Great, thanks, what steps will be involved?

**Comment by jwokaty** [comment]
I thought it might be more involved, but it seems pretty straightforward and I can do it this week.

- [x] Stop GitHub Actions
- [x] Rename main to devel
- [x] Change main to devel in the GH workflow
- [x] Restart GitHub Action
- [x] Remove Line 31 in bugsigdbr
