### ISSUE TITLE
Update only if content changes

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/BugSigDBExports#29]

**Comment by lwaldron** [comment]
Here's an example of file `bugsigdb_signatures_species_taxname_exact.gmt` where the only change is the timestamp: https://github.com/waldronlab/BugSigDBExports/commit/8b5209cb8bede0aef5660cd4036ee2421c2d8324#diff-727d4d83f15c1cff5d9a31735b01e49ce8f0424eda486feec43adeca2e1742e6
