### ISSUE TITLE
BugSigDB 1.0 release

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDBExports#4]
Hi @jwokaty:

@lwaldron and I had started to discuss a release scheme for BugSigDB.

One idea was to follow Bioconductor's semi-annual release scheme, and have a stable release of BugSigDB signatures every half a year. We also discussed [zenodo](https://zenodo.org/) as the platform for hosting the stable release (= csv files for studies, experiments, and signatures).

A stable release is supposed to contain *all reviewed* content from BugSigDB up to a defined freeze date. For the BugSigDB 1.0 release this could encompass reviewed content up to the present date for simplicity, or if we wanted to synchronize with Bioconductor, up to the past 3.13 release date.

Would you like to go ahead and export the content, filter by date and review status, upload to zenodo, and include the stable release link under https://bugsigdb.org/Help:Export ?

Thanks!

**Comment by lwaldron** [comment]
Sorry for being impatient and just transferring it, was only so I could refer to it from https://github.com/waldronlab/BugSigDB/issues/92 (although I just learned that those references get automatically updated with the transfer!)

**Comment by lwaldron** [comment]
I set up the Zenodo integration and did a little debugging trying to get it to work (https://zenodo.org/account/settings/github/repository/waldronlab/BugSigDBExports#) but am stuck now with the following error on Zenodo:

```json
{
    "errors": "Something went wrong when we tried to publish your release. If your release has not been published within the next hour, please contact us via our support form to resolve this issue."
}
```

Let's see if it fixes itself within the next hour, otherwise I'll contact the Zenodo support team. It's very particular about the .zenodo.json file.

**Comment by lgeistlinger** [comment]
@jwokaty @lwaldron quick update: I incorporated a filter for complete content in the dump release script, so the only thing remaining for the 1.0 release to zenodo is to clean up are the ontology columns (https://github.com/waldronlab/BugSigDB/issues/92#issuecomment-916309509). Will work on that so that we get that through the door prior to the October Bioc release.

**Comment by jwokaty** [comment]
Hi @lgeistlinger, there's an issue with automatically releasing to Zenodo, so we should do a manual release of the files. (The last I heard from them, they were still working on it last week.) What is the date that we will do the release, Oct. 25? And do want to modify https://github.com/waldronlab/bugsigdbr to get data from Zenodo (along with the bleeding edge)?

**Comment by lgeistlinger** [comment]
> And do want to modify https://github.com/waldronlab/bugsigdbr to get data from Zenodo (along with the bleeding edge)?

And yes, that is what I think we are aiming for. Being able to pull the zenodo release (stable) as well as the continously updated version (bleeding edge) from BugSigDBExports as we do it currently, if that makes sense.

**Comment by lgeistlinger** [comment]
Hi @jwokaty @lwaldron : this is finally ready for release! we [finished the ontology columns in the export](https://github.com/waldronlab/BugSigDB/issues/92#issuecomment-997450272) and everything is looking good now for upload of the stable BugSigDB 1.0 release to zenodo. @jwokaty can you go ahead and perform the upload to zenodo? (Not sure whether this will involve overwriting your previous upload under https://zenodo.org/record/5606166, or whether we bump this to 1.0.1 then). Thanks!

**Comment by lgeistlinger** [comment]
The release should be accordingly based on the latest export: 1137470

**Comment by jwokaty** [comment]
@lgeistlinger We have to bump the version to 1.0.1. I just want to check if there should be a specific release title and any description for the release before I create the release. Also, would you like me to 'draft' the upload in Zenodo so that you can take a look before I finalize everything?

**Comment by lgeistlinger** [comment]
Thanks @jwokaty! I noticed a small inconvenience in the bulk export from bugsigdb.org, with some conditions / body sites being present in upper case and lower case (eg "Feces" and "feces"). I introduced a small fix for that in 121c571. Can you trigger a manual export for that and base the 1.0.1 on this export? 

> if there should be a specific release title and any description for the release before I create the release

Nothing specific here from my side.

> Also, would you like me to 'draft' the upload in Zenodo so that you can take a look before I finalize everything?

That sounds like a good idea!

**Comment by lgeistlinger** [comment]
Hi @jwokaty - I just took a look at yesterday's export (3def7c9) and everything looks good for upload / release to zenodo. Just let me know if you have any questions. Many thanks!

**Comment by jwokaty** [comment]
@lgeistlinger I've drafted the new version at https://zenodo.org/deposit/5819260. (I am assuming that you can see it.)

**Comment by lgeistlinger** [comment]
Thanks @jwokaty , logging in to zenodo via Github (lgeistlinger / ludwig.geistlinger@gmail.com),  I am seeing:

`Permission required: You do not have sufficient permissions to view this page.`

**Comment by jwokaty** [comment]
I apologize. I thought maybe because we had access to the same thing that maybe we could all see the draft. Maybe there's no way for you to see it? I just updated all the files, except for the README, and then updated the version number to v1.0.1.

**Comment by lgeistlinger** [comment]
> I just updated all the files, except for the README, and then updated the version number to v1.0.1.

Cool! Can you maybe share the files via google drive or dropbox with me to quickly review them on my end. Thanks!

**Comment by jwokaty** [comment]
The files are the same as in this release: https://github.com/waldronlab/BugSigDBExports/releases/tag/v1.0.1

**Comment by lgeistlinger** [comment]
Ah very nice, somehow I didn't notice the `releases` folder/branch. Cool, I'd say good to go to upload to zenodo and closing this issue.
